Feature/9
depromeet/toks-api pull request #18
Opened 2022-11-16 09:38 UTC by SieunKiim

## ✔️ PR 타입
- 기능

## 📃 개요
- 카카오 소셜 로그인 구현
- 카카오를 통해 사용자 정보 조회
- 사용자 저장 및 닉네임 설정

## ✏️ 변경사항
- UserEntity 변경
- SpringSecurity config 변경

## 🫥 TODO
- 프론트 url 적용
- 토큰 재발급 및 갱신 로직
- 1차 배포 (프론트에서 원하시더라구요)

2022-11-16 14:23 UTC, south-daria reviewed
수고하셨습니다 ~ 코멘트 남긴 부분 확인 부탁드려요:)

2022-11-16 14:23 UTC, south-daria commented on api/src/main/java/com/tdns/toks/api/domain/user/controller/UserController.java
> +            @ApiResponse(responseCode = "200", description = "successful operation", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = JwtToken.class))}),
swagger schema가 다른 것 같아요. 확인해주세요!

2022-11-16 14:23 UTC, south-daria commented on api/src/main/java/com/tdns/toks/api/domain/user/service/UserApiService.java
> +        UserDTO userDto = (UserDTO)authentication.getPrincipal();
SecurityContextHolder에서 User가지고 오는 부분 자주 쓰일 것 같아서 UserDetailDTO나 UserDTO에 static 메소드로 빼는 게 좋을 것 같아요

2022-11-16 14:23 UTC, south-daria commented on api/src/main/java/com/tdns/toks/api/domain/user/service/UserApiService.java
> +        User user = userService.updateNickname(userDto.getEmail(), userUpdateNicknameRequest.getNickname());
email 말고 id를 넘겨주는 게 더 명확할 것 같아요.

2022-11-16 14:23 UTC, south-daria commented on api/src/main/java/com/tdns/toks/api/domain/user/service/UserApiService.java
>      public JwtToken login(UserLoginRequest userLoginRequest) {
해당 메소드 convertToUserEntity랑 같이 지워주세요

2022-11-16 14:23 UTC, south-daria commented on api/src/main/resources/application.yml
> +      front-redirect-uri: http://localhost:8080/login/kakaoauth
application.yml이 아니라 local, dev, stage 별로 정의해주어야할 것 같아요.

2022-11-16 14:23 UTC, south-daria commented on api/src/main/resources/application.yml
> +  port: 8080
제 포트 날려버리셨네요

2022-11-16 14:23 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/CustomOAuth2UserService.java
> +        log.info(oAuth2User.toString());
필요한 로그라면, json 형태로 한번에 로그 쌓아주시는 게 나중에 로그확일할 때 편할 것 같아요.

2022-11-16 14:23 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/CustomOAuth2UserService.java
> +        log.info(oAuth2User.toString());
사람마다 다르기 때문에 필수는 아닙니다.

2022-11-16 14:23 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2Attribute.java
> +    static OAuth2Attribute of(String provider, Map<String, Object> attributes) {
생성자 메소드 어떻게 할 건지 한번 정의하는 게 좋을 것 같네요.

2022-11-16 14:23 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2Attribute.java
> +                throw new RuntimeException("등록되지 않은 Provider : " + provider);
runTimeException이 아니라 silentException으로 바꿔주시면 좋을 것 같아요

2022-11-16 14:23 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2FailureHandler.java
> +        log.info("[OAuth2FailureHandler] 인증 실패");
log 보다는 exception을 던지는 게 더 좋을 것 같아요.

2022-11-16 14:23 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/domain/user/model/dto/UserDetailDTO.java
> -        return user.getUpwd();
해당 부분에는 왜 null을 리턴하는지 주석 달아주면 좋을 것 같아요.

2022-11-16 14:23 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/domain/user/model/dto/UserDetailDTO.java
> +        return OAuth2User.super.getAttribute(name);
UserDetailDTO에 attributes가 아닌 super의 attribute를 리턴하는 이유가 있을까요?(잘못됐다는게 아니라 궁금해서 여쭤보는 거에요)

2022-11-16 14:23 UTC, south-daria commented on flyway/build.gradle
> -        set('mysqlUsername', mysqlUsername)
build.gradle 원복해주세요

2022-11-16 14:23 UTC, south-daria commented on flyway/build.gradle
> +        set('mysqlPassword', "1234")
비밀번호 함부로 push 하고 그러시면 안됩니다.. 요기 public이여요!

2022-11-17 04:08 UTC, south-daria requested changes

2022-11-17 04:08 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/domain/user/service/UserService.java
> +        user.updateNickname(nickname);
닉네임 중복확인 부분이 없는 것 같네요

2022-11-17 06:03 UTC, SieunKiim commented on api/src/main/java/com/tdns/toks/api/domain/user/service/UserApiService.java
> +        UserDTO userDto = (UserDTO)authentication.getPrincipal();
찾다보니 UserDetailDTO에 SecurityContextHolder에서 UserDTO를 가져오는 static 메서드(get())가 있는데 이 부분 활용해서 수정해봐도 괜찮을까요?

2022-11-17 06:10 UTC, SieunKiim commented
아하..! 로그아웃도 구현해야하는군요..! 🫡

2022-11-17 08:26 UTC, SieunKiim commented on api/src/main/resources/application.yml
> +  port: 8080
😂

2022-11-17 08:45 UTC, SieunKiim commented on flyway/build.gradle
> +        set('mysqlPassword', "1234")
아앗 jasypt로 돌렸슴다..! 🙈

2022-11-17 10:18 UTC, DongGeon0908 reviewed
고생하셨습니다

2022-11-17 10:18 UTC, DongGeon0908 commented on api/src/main/java/com/tdns/toks/api/domain/user/service/UserApiService.java
>          User user = userService.getUser(userLoginRequest.getProvider(), userLoginRequest.getProviderId());
```suggestion
        var user = userService.getUser(userLoginRequest.getProvider(), userLoginRequest.getProviderId());
```

2022-11-17 10:18 UTC, DongGeon0908 commented on api/src/main/java/com/tdns/toks/api/domain/user/service/UserApiService.java
> +        UserDTO userDto = (UserDTO)authentication.getPrincipal();
```suggestion
        var authentication = SecurityContextHolder.getContext().getAuthentication();
        var userDto = (UserDTO)authentication.getPrincipal();
```

2022-11-17 10:18 UTC, DongGeon0908 commented on api/src/main/resources/application.yml
> +            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
이거 노출해도 되나요???

2022-11-17 10:18 UTC, DongGeon0908 commented on api/src/main/resources/application.yml
>      secret: ENC(BF9EmOQPpQJ8n8uZwUgw37wHFDBQg9wCNHiZUcDnNTbQbHwUd//RIfjiCO38GavO7PIuCKm11FFVhKG1HofyiljZBCCD83eOzw9lWZi6VXE=)
해당 값 외부로 노출해도 되는 걸까요??

2022-11-17 10:18 UTC, DongGeon0908 commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2SuccessHandler.java
> +        String url = setRedirectUrl(jwtTokenProvider.generateToken(email));
```suggestion
        var email = authentication.getName();
        var url = setRedirectUrl(jwtTokenProvider.generateToken(email));
```

2022-11-17 10:18 UTC, DongGeon0908 commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2SuccessHandler.java
> +        String refreshToken = jwtToken.getRefreshToken();
```suggestion
        var accessToken = jwtToken.getAccessToken();
        var refreshToken = jwtToken.getRefreshToken();
```

2022-11-17 10:18 UTC, DongGeon0908 commented on core/src/main/java/com/tdns/toks/core/config/security/AuthSecurityConfig.java
> +                    .anyRequest().permitAll()
모든 api가 인증인가가 필요하나요??

2022-11-17 10:18 UTC, DongGeon0908 commented on flyway/src/main/resources/db/migration/schema/V1.0__createTableUser.sql
>  CREATE TABLE `user` (
auto-increment를 20000부터 시작하는건 어떨까요?

2022-11-17 11:54 UTC, SieunKiim commented on core/src/main/java/com/tdns/toks/core/domain/user/model/dto/UserDetailDTO.java
> +        return OAuth2User.super.getAttribute(name);
필수 오버라이드 항목 자동완성으로 들어와서 그대로 사용했습니다..! 🥲

2022-11-17 12:57 UTC, SieunKiim commented on api/src/main/resources/application.yml
>      secret: ENC(BF9EmOQPpQJ8n8uZwUgw37wHFDBQg9wCNHiZUcDnNTbQbHwUd//RIfjiCO38GavO7PIuCKm11FFVhKG1HofyiljZBCCD83eOzw9lWZi6VXE=)
user-name-aattribute 값은 provider에서 제공하는 id가 값을 기준으로 가져온다는 표현으로 이해하고 있습니다. 노출돼도 문제가 없다고 생각했습니다..!

2022-11-17 13:01 UTC, SieunKiim commented on api/src/main/resources/application.yml
> +            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
client-id는 암호화 통해서 안전하다고 생각했었는데 혹시 redirect-uri도 노출 시 문제가 될까요..? 참고했던 레퍼런스들도 노출되어 있어서 미처 신경쓰지 못했습니다..🥲

2022-11-17 15:23 UTC, DongGeon0908 commented on api/src/main/resources/application.yml
> +            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
가능하면, 노출하지 않는게 좋긴해용

2022-11-17 15:23 UTC, DongGeon0908 commented on api/src/main/resources/application.yml
>      secret: ENC(BF9EmOQPpQJ8n8uZwUgw37wHFDBQg9wCNHiZUcDnNTbQbHwUd//RIfjiCO38GavO7PIuCKm11FFVhKG1HofyiljZBCCD83eOzw9lWZi6VXE=)
아! Jwt Secret이요!

2022-11-18 04:11 UTC, hocaron reviewed
고생 많으셨습니다👍👍👍
다른 분들이 남겨주신 리뷰 외에 이견 없습니다!

2022-11-18 10:34 UTC, south-daria commented on api/src/main/java/com/tdns/toks/api/domain/user/service/UserApiService.java
> +        UserDTO userDto = (UserDTO)authentication.getPrincipal();
네네 좋아요~ 머지된 거 있으니 develop에서 pull한번 받아주세욤

2022-11-18 13:04 UTC, SieunKiim commented on api/src/main/java/com/tdns/toks/api/domain/user/service/UserApiService.java
> +        UserDTO userDto = (UserDTO)authentication.getPrincipal();
하아잇! (사랑쨩 톤으로)

2022-11-18 15:55 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/domain/user/service/UserService.java
> +    public boolean isNicknameDuplicated(String nickname) {
private 메소드로 변경하는 게 더 좋아보이네요.

2022-11-18 15:55 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/config/security/AuthSecurityConfig.java
> +                    .antMatchers(permitUrl).permitAll()
antMatchers(permitUrl).permitAll().
anyRequest.authenticated() 
로 수정하는 게 좋을 것 같아요.
antMatchers GET, POST, DELETE, PUT, PATCH 부분 필요없을 것 같아요.

2022-11-18 15:55 UTC, south-daria commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2FailureHandler.java
> +        log.info("[OAuth2FailureHandler] 인증 실패");
수정 안된 것 같은데 닫혀있어서 다시 열었습니다 !

2022-11-19 01:17 UTC, SieunKiim commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2FailureHandler.java
> +        log.info("[OAuth2FailureHandler] 인증 실패");
아앗..! exception 던지는 방향으로 수정했습니다!

2022-11-21 01:04 UTC, DongGeon0908 reviewed
고생하셨습니다!

2022-11-21 01:04 UTC, DongGeon0908 commented on core/src/main/java/com/tdns/toks/core/domain/user/service/UserService.java
> +        return usedNickname.isPresent();
existsByNickname을 사용하는게 좋을 것 같아요

2022-11-21 01:04 UTC, DongGeon0908 commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/OAuth2SuccessHandler.java
> +        var url = setRedirectUrl(userDetailDTO.getJwtToken());
var keyword 통일이 필요할 것 같아요!

2022-11-21 01:04 UTC, DongGeon0908 commented on core/src/main/java/com/tdns/toks/core/common/security/oauth/CustomOAuth2UserService.java
> +    }
한번 정리하는게 어떨까요?? 지금은 읽기 어려운 것 같아요 ㅜㅜ

2022-11-21 01:04 UTC, DongGeon0908 commented on api/src/main/resources/application.yml
>      host: 127.0.0.1
redis의 경우 추후에 elc로 바꾸는 건 어떨까요?

2022-11-21 09:39 UTC, south-daria commented on api/src/main/resources/application.yml
>      host: 127.0.0.1
elastic cache 말씀하시는 거죠?
한 번도 안 써봤는데, 커맨드가 많이 다른가요?

2022-11-22 04:44 UTC, DongGeon0908 commented on api/src/main/resources/application.yml
>      host: 127.0.0.1
아니요 같아용~
aws에서 바로 생성해서 붙이면 됩니당~

2022-11-22 04:45 UTC, DongGeon0908 commented on api/src/main/resources/application.yml
>      host: 127.0.0.1
현재 구조는 ec2 local에서 redis를 돌리고 있는데요
만약에 ec2가 다운되는 상황이 발생한다면, redis도....나락으로..
이런 상황을 방지하기 위해서 redis 서버를 분리해서 사용하는게 좋아욤

2022-11-24 05:20 UTC, south-daria commented on api/src/main/resources/application.yml
>      host: 127.0.0.1
네네 리서치 해보고 팀 분들이랑 상의해보겠습니당

2022-11-24 05:22 UTC, south-daria approved these changes

2022-11-24 05:56 UTC, DongGeon0908 reviewed
고생하셨습니다!
oauth의 경우, 실제 서비스에서 사용할려면 별도의 신청이 필요한데, 신청이 되었을까용??

2022-11-24 07:49 UTC, south-daria commented
> 고생하셨습니다! oauth의 경우, 실제 서비스에서 사용할려면 별도의 신청이 필요한데, 신청이 되었을까용??

일단 로컬 환경만 되어있는 걸로 알고 있는데, 시은님께 한번 확인요청 드리겠습니다

2022-11-26 00:46 UTC, SieunKiim commented
> 사용할려면 별도의 신청이 필요한데, 신청이 되었을까용
카카오 로그인 api 관련해서 별도 신청 페이지나 안내 사항이 보이지 않아서, redirect URL과 사이트 도메인만 설정 해주면 될 듯 합니다!

2022-11-26 15:37 UTC, hocaron approved these changes
고생 많으셨습니다👍👍👍

2022-11-26 15:41 UTC, hocaron commented on flyway/src/main/resources/application.yml
> +    password: ENC(drZoLtxSspNJRGx7v+G7OwUiZkFMRFZtf8gKpFAt3Pf4yc39vOzi9b7xQcD2nnkk)
이 부분은 어떤 데이터 인지 궁금합니다🙋‍♀️

2022-11-27 04:28 UTC, SieunKiim commented on flyway/src/main/resources/application.yml
> +    password: ENC(drZoLtxSspNJRGx7v+G7OwUiZkFMRFZtf8gKpFAt3Pf4yc39vOzi9b7xQcD2nnkk)
앗! 따로 건드린 기억은 없는데... 혹시 pull 가져올 때 제가 실수한 듯 합니다...!😢
develop 브랜치 있는 대로 수정하면 괜찮을까요?!

2022-11-28 00:21 UTC, hocaron commented on flyway/src/main/resources/application.yml
> +    password: ENC(drZoLtxSspNJRGx7v+G7OwUiZkFMRFZtf8gKpFAt3Pf4yc39vOzi9b7xQcD2nnkk)
오 그렇군요:)
local, dev 가져오면서 덥어씌여질 것 같긴하지만, 지워주셔도 좋을 것 같습니다😀

2022-11-28 03:12 UTC, SieunKiim commented on flyway/src/main/resources/application.yml
> +    password: ENC(drZoLtxSspNJRGx7v+G7OwUiZkFMRFZtf8gKpFAt3Pf4yc39vOzi9b7xQcD2nnkk)
넵 반영했습니다!

2022-11-28 04:19 UTC, merged